#!/usr/bin/env bash
# A script that transfers a file from our client to my server
# Print Usage if 4 parameters are not provided
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign the parameters
path_to_file=$1
ip=$2
user=$3
path_to_ssh=$4

# Disable strict host key checking
export "SCP_OPTIONS=-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$path_to_ssh" $path_to_file $user@$ip:~/
