#!/usr/bin/env bash
# A script that Installs nginx web server to another server then Redirects it
# to another page

# Update package lists
sudo apt update

# Install Nginx isiing -y to prompt yes
sudo apt install -y nginx

# Create a simple HTML page
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx to redirect
sudo sed -i "/listen \[::\]:80 default_server;/a rewrite ^/redirect_me https://www.google.com/ permanent;" /etc/nginx/sites-available/default

# Restart Nginx on server
sudo service nginx restart
