#!/usr/bin/env bash
# A script that Installs nginx web server to another server then Redirects it
# to another page

# Update package lists
sudo apt update

# Install Nginx isiing -y to prompt yes
sudo apt install -y nginx

# Configire Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a simple HTML page
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx to redirect
line1="\\tlocation \/redirect_me "
line2=" return 301 "
location="/etc/nginx/sites-available/default"
# Configure Nginx to resolve Not found page 404
echo "301 Moved Permanently" | sudo tee /var/www/html/301.html >> /dev/null
sudo sed -i "/^server {/a $line1{\n\t\t$line2/301.html;\n\t}" $location

# Restart Nginx on server
sudo service nginx restart
