#!/usr/bin/env bash
# A script that Installs nginx web server to another server then Redirects it
# to another page and if page is not found it prints "Ceci n'est pas une page"

# Update package lists
sudo apt update

# Install Nginx isiing -y to prompt yes
sudo apt install -y nginx

# Configire Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a simple HTML page
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx to redirect
sudo sed -i "/listen \[::\]:80 default_server;/a rewrite ^/redirect_me https://www.google.com/ permanent;" /etc/nginx/sites-available/default

# Configure Nginx to resolve Not found page 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo sed -i "/^server {/a \terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t}" /etc/nginx/sites-available/default

# Restart Nginx on server
sudo service nginx restart
