#!/usr/bin/env bash
# A script that Install and configure HAproxy on your lb-01 server

# Enable a dedicated PPA
sudo pt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8sudo apt update -y

# Install HAProxy
sudo apt-get install -y haproxy=2.8.\*

# Configire HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg

# Configure HAproxy for web-01 and web--02

echo "frontend lb_frontend
	bind *:80
	mode http
	default_backend lb_backend
	
backend lb_backend
	balance roundrobin
	server web-01 230448-web-01:80
	server web-02 230448-web-02:80" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy on server
sudo service haproxy restart
