#!/usr/bin/env bash
# A script that Install and configure HAproxy on your lb-01 server

# Update the system
sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install -y haproxy

# Configire HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg

# Configure HAproxy for web-01 and web--02

echo "frontend lb_frontend
        bind *:80
        mode http
        default_backend lb_backend

backend lb_backend
        balance roundrobin
        server 230448-web-01 54.157.137.159:80
        server 230448-web-02 54.210.88.23:80" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy on server
sudo service haproxy restart
