#!/usr/bin/env bash
# Bash script that runs nginx as nginx user and must be listening on all active IPs on port 8080
sudo service nginx stop
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
sudo service nginx start
